---
version: 2
executorType: docker
containerInfo:
  - image: dickeyxxx/cli-engine@sha256:090e7e327787303491f27482f021b9fbcfeac1d379a20769c7524c1c53b68c88
stages:
  build:
    workDir: ~/cli-engine-example
    environment:
      - CIRCLE_PROJECT_USERNAME: dickeyxxx
      - CIRCLE_PROJECT_REPONAME: cli-engine-example
      - HEROKU_DEBUG: 1
    steps:
      - type: checkout
      - type: cache-restore
        key: cli-engine-example{{checksum "package.json"}}
      - type: shell
        command: |
          set -exu

          yarn --prefer-offline --pure-lockfile
          ./node_modules/.bin/jest

      - type: test-results-store
        path: /tmp/test-results
      - type: cache-save
        key: cli-engine-example{{checksum "package.json"}}
        paths:
          - /usr/local/share/.cache/yarn
